backend:
  name: github
  repo: Hesi777/nanodent
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "cennik"
    label: "Cennik"
    folder: "data"
    create: false
    slug: "cennik"
    format: "frontmatter"
    fields:
      - { label: "Treść", name: "body", widget: "markdown" }
