backend:
  name: git-gateway
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "cennik"
    label: "Cennik"
    files:
      - label: "Cennik główny"
        name: "cennik"
        file: "data/cennik.md"
        fields:
          - { label: "Treść", name: "body", widget: "markdown" }
